import { FormEvent, useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { AlertTriangle, CheckCircle2, Clock3, FileCheck2, Plus, ReceiptText, Search } from 'lucide-react';
import { DivisionPageHeader } from '../../../components/ui/DivisionPageHeader';
import { Button } from '../../../components/ui/Button';
import { ErrorState, LoadingState } from '../../../components/states';
import { useAuth } from '../../../session/AuthContext';
import { cellularApi, type DailyClosing } from '../api';

const today = () => new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Jakarta', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date());
const money = (value: string | number) => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(Number(value));
const statusLabel: Record<DailyClosing['status'], string> = { draft: 'Draf', submitted: 'Menunggu Accounting', validated: 'Menunggu Manager', approved: 'Disetujui', correction: 'Perlu Koreksi' };
const statusClass: Record<DailyClosing['status'], string> = { draft: 'bg-surface text-subtle', submitted: 'bg-warning-light text-warning-dark', validated: 'bg-primary-50 text-primary-700', approved: 'bg-success-light text-success', correction: 'bg-danger-light text-danger' };
const field = 'min-h-10 w-full rounded-input border border-line bg-panel px-3 text-sm text-navy outline-none focus:border-primary-500 focus:ring-2 focus:ring-primary-100';

export default function CellularDailyClosingPage() {
  const { user } = useAuth(); const qc = useQueryClient();
  const [month, setMonth] = useState(today().slice(0, 7)); const [search, setSearch] = useState(''); const [showForm, setShowForm] = useState(false); const [note, setNote] = useState('');
  const [form, setForm] = useState({ outlet_id: '', business_date: today(), shift_code: 'SHIFT-1', cash: '0', qris: '0', edc: '0', transfer: '0', source_reference: '' });
  const closings = useQuery({ queryKey: ['cellular', 'daily-closings', month], queryFn: () => cellularApi.dailyClosings(month) });
  const outlets = useQuery({ queryKey: ['cellular', 'outlets'], queryFn: cellularApi.outlets });
  const mutation = useMutation({ mutationFn: async (input: { kind: 'save'; data: typeof form } | { kind: 'action'; row: DailyClosing; action: 'submit' | 'validate' | 'approve' | 'correction' }) => input.kind === 'save' ? cellularApi.saveDailyClosing(input.data) : cellularApi.transitionDailyClosing(input.row, input.action, note), onSuccess: async () => { await qc.invalidateQueries({ queryKey: ['cellular', 'daily-closings'] }); setShowForm(false); setNote(''); setForm(value => ({ ...value, source_reference: '', cash: '0', qris: '0', edc: '0', transfer: '0' })); } });
  const rows = closings.data?.data ?? [];
  const metrics = useMemo(() => ({ total: rows.reduce((sum, row) => sum + Number(row.system_sales), 0), difference: rows.reduce((sum, row) => sum + Number(row.difference), 0), pending: rows.filter(row => ['submitted', 'validated'].includes(row.status)).length, approved: rows.filter(row => row.status === 'approved').length }), [rows]);
  const filtered = rows.filter(row => `${row.business_date} ${row.shift_code} ${row.source_reference} ${statusLabel[row.status]}`.toLowerCase().includes(search.toLowerCase()));
  if (closings.isLoading || outlets.isLoading) return <LoadingState label="Memuat penerimaan harian..." />;
  if (closings.error || outlets.error) return <ErrorState title="Penerimaan harian gagal dimuat" description={(closings.error ?? outlets.error)?.message ?? 'Data tidak tersedia.'} onRetry={() => { void closings.refetch(); void outlets.refetch(); }} />;
  const role = user?.role ?? '';
  const submit = (event: FormEvent) => { event.preventDefault(); mutation.mutate({ kind: 'save', data: form }); };
  const act = (row: DailyClosing, action: 'submit' | 'validate' | 'approve' | 'correction') => mutation.mutate({ kind: 'action', row, action });

  return <div className="space-y-6 pb-10 animate-fade-in">
    <DivisionPageHeader division="Divisi Cellular" descriptor="Penerimaan Harian · Tutup Shift" title="Rekap Penerimaan Harian" description="Cocokkan omzet sistem dengan tunai, QRIS, EDC, dan transfer sebelum pemeriksaan Accounting serta persetujuan Manager." actions={role === 'ADMIN' ? <Button onClick={() => setShowForm(value => !value)}><Plus className="h-4 w-4" />Catat penerimaan</Button> : undefined} />

    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
      <Metric label="Omzet sistem" value={money(metrics.total)} note={`${rows.length} tutup shift`} icon={<ReceiptText />} primary />
      <Metric label="Selisih kanal" value={money(metrics.difference)} note="Pembayaran dikurangi omzet" icon={<AlertTriangle />} danger={metrics.difference !== 0} />
      <Metric label="Menunggu tindakan" value={metrics.pending} note="Accounting atau Manager" icon={<Clock3 />} />
      <Metric label="Disetujui" value={metrics.approved} note="Siap masuk pembukuan" icon={<CheckCircle2 />} />
    </div>

    {showForm && role === 'ADMIN' && <form onSubmit={submit} className="rounded-card border border-line bg-panel p-5 shadow-card"><div className="mb-5 flex items-center justify-between"><div><h2 className="font-bold text-navy">Tutup shift baru</h2><p className="mt-1 text-xs text-subtle">Omzet sistem dihitung otomatis dari penjualan posted pada outlet dan tanggal yang dipilih.</p></div><button type="button" className="text-sm text-subtle" onClick={() => setShowForm(false)}>Tutup</button></div><div className="grid gap-4 md:grid-cols-3"><Field label="Outlet"><select required className={field} value={form.outlet_id} onChange={e => setForm({ ...form, outlet_id: e.target.value })}><option value="">Pilih outlet</option>{outlets.data?.data.map(row => <option key={row.id} value={row.id}>{row.name}</option>)}</select></Field><Field label="Tanggal bisnis"><input required type="date" max={today()} className={field} value={form.business_date} onChange={e => setForm({ ...form, business_date: e.target.value })} /></Field><Field label="Shift"><input required className={field} value={form.shift_code} onChange={e => setForm({ ...form, shift_code: e.target.value })} /></Field>{(['cash','qris','edc','transfer'] as const).map(key => <Field key={key} label={key.toUpperCase()}><input required inputMode="decimal" pattern="\d{1,12}(\.\d{1,2})?" className={field} value={form[key]} onChange={e => setForm({ ...form, [key]: e.target.value })} /></Field>)}<Field label="Referensi laporan"><input required className={field} value={form.source_reference} onChange={e => setForm({ ...form, source_reference: e.target.value })} /></Field></div>{mutation.error && <p role="alert" className="mt-4 rounded-input bg-danger-light p-3 text-sm text-danger">{mutation.error.message}</p>}<div className="mt-5 flex justify-end"><Button disabled={mutation.isPending} type="submit">{mutation.isPending ? 'Menyimpan...' : 'Simpan draf'}</Button></div></form>}

    <section className="overflow-hidden rounded-card border border-line bg-panel shadow-card"><div className="flex flex-col gap-4 border-b border-line p-5 md:flex-row md:items-center md:justify-between"><div><h2 className="font-bold text-navy">Register tutup shift</h2><p className="mt-1 text-xs text-subtle">Alur: Admin → Accounting → Manager</p></div><div className="flex gap-3"><label className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-muted" /><input aria-label="Cari penerimaan" className={`${field} pl-9`} placeholder="Cari tanggal, shift, referensi" value={search} onChange={e => setSearch(e.target.value)} /></label><input aria-label="Periode penerimaan" type="month" className={`${field} w-auto`} value={month} onChange={e => setMonth(e.target.value)} /></div></div><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="bg-surface text-[11px] uppercase tracking-wider text-subtle"><tr><th className="px-5 py-3">Tanggal / Shift</th><th>Omzet Sistem</th><th>Rincian Pembayaran</th><th>Selisih</th><th>Status</th><th>Referensi</th><th className="pr-5">Tindakan</th></tr></thead><tbody className="divide-y divide-line">{filtered.map(row => <tr key={row.id} className="hover:bg-surface/60"><td className="px-5 py-4"><p className="font-semibold text-navy">{row.business_date}</p><p className="text-xs text-subtle">{row.shift_code}</p></td><td className="font-bold tabular-nums text-navy">{money(row.system_sales)}</td><td className="text-xs leading-5 text-subtle">Tunai {money(row.cash)} · QRIS {money(row.qris)}<br/>EDC {money(row.edc)} · Transfer {money(row.transfer)}</td><td className={`font-bold tabular-nums ${Number(row.difference) === 0 ? 'text-success' : 'text-danger'}`}>{money(row.difference)}</td><td><span className={`rounded-pill px-2.5 py-1 text-xs font-bold ${statusClass[row.status]}`}>{statusLabel[row.status]}</span>{row.review_note && <p className="mt-2 max-w-48 text-xs text-danger">{row.review_note}</p>}</td><td className="max-w-48 truncate text-subtle">{row.source_reference}</td><td className="pr-5"><Actions row={row} role={role} busy={mutation.isPending} act={act} note={note} setNote={setNote} /></td></tr>)}</tbody></table></div>{!filtered.length && <div className="p-10 text-center"><FileCheck2 className="mx-auto h-8 w-8 text-muted"/><p className="mt-3 text-sm font-semibold text-navy">Belum ada penerimaan</p><p className="mt-1 text-xs text-subtle">Pilih periode lain atau buat tutup shift baru.</p></div>}</section>
  </div>;
}

function Metric({ label, value, note, icon, primary, danger }: { label: string; value: string | number; note: string; icon: React.ReactNode; primary?: boolean; danger?: boolean }) { return <article className={`rounded-card border p-5 shadow-card ${primary ? 'border-primary-600 bg-gradient-to-br from-primary-600 to-primary-800 text-white' : 'border-line bg-panel'}`}><div className="flex items-start justify-between"><div><p className={`text-xs font-semibold uppercase tracking-wider ${primary ? 'text-primary-100' : 'text-subtle'}`}>{label}</p><p className={`mt-2 text-2xl font-bold ${primary ? 'text-white' : danger ? 'text-danger' : 'text-navy'}`}>{value}</p></div><span className={`flex h-10 w-10 items-center justify-center rounded-input ${primary ? 'bg-white/15' : 'border border-line bg-surface text-primary-600'}`}>{icon}</span></div><p className={`mt-3 text-xs ${primary ? 'text-primary-100' : 'text-subtle'}`}>{note}</p></article>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="text-xs font-semibold text-subtle">{label}<span className="mt-1.5 block">{children}</span></label>; }
function Actions({ row, role, busy, act, note, setNote }: { row: DailyClosing; role: string; busy: boolean; act: (row: DailyClosing, action: 'submit' | 'validate' | 'approve' | 'correction') => void; note: string; setNote: (value: string) => void }) { if (role === 'ADMIN' && ['draft','correction'].includes(row.status)) return <button disabled={busy} onClick={() => act(row, 'submit')} className="font-semibold text-primary-700">Ajukan</button>; if (role === 'ACCOUNTING' && row.status === 'submitted') return <div className="flex max-w-60 items-center gap-2"><input aria-label={`Catatan ${row.id}`} className="min-h-9 w-28 rounded-input border border-line px-2 text-xs" placeholder="Alasan koreksi" value={note} onChange={e => setNote(e.target.value)} /><button disabled={busy} onClick={() => act(row, 'validate')} className="font-semibold text-success">Validasi</button><button disabled={busy || !note.trim()} onClick={() => act(row, 'correction')} className="font-semibold text-danger">Koreksi</button></div>; if (role === 'MANAGER' && row.status === 'validated') return <button disabled={busy} onClick={() => act(row, 'approve')} className="font-semibold text-primary-700">Setujui</button>; return <span className="text-xs text-muted">Tidak ada tindakan</span>; }
