import { FormEvent, useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { AlertTriangle, CheckCircle2, ClipboardCheck, Clock3, Plus, Search, ShieldCheck } from 'lucide-react';
import { DivisionPageHeader } from '../../../components/ui/DivisionPageHeader';
import { Button } from '../../../components/ui/Button';
import { ErrorState, LoadingState } from '../../../components/states';
import { useAuth } from '../../../session/AuthContext';
import { cellularApi, type ShiftControl } from '../api';

const today = () => new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Jakarta', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date());
const field = 'min-h-10 w-full rounded-input border border-line bg-panel px-3 text-sm text-navy outline-none focus:border-primary-500 focus:ring-2 focus:ring-primary-100';
const checkLabels: Record<keyof ShiftControl['checklist'], string> = { handover_complete: 'Serah terima shift lengkap', stock_count_complete: 'Hitung stok selesai', payment_channels_ready: 'Kanal pembayaran siap', closing_matched: 'Closing cocok dengan sumber' };
const statusLabel: Record<ShiftControl['status'], string> = { draft: 'Draf Leader', submitted: 'Menunggu SPV', reviewed: 'Menunggu Head Ops', correction: 'Perlu Koreksi', escalated: 'Eskalasi Manager', resolved: 'Selesai' };
const statusClass: Record<ShiftControl['status'], string> = { draft: 'bg-surface text-subtle', submitted: 'bg-warning-light text-warning-dark', reviewed: 'bg-primary-50 text-primary-700', correction: 'bg-danger-light text-danger', escalated: 'bg-danger-light text-danger', resolved: 'bg-success-light text-success' };
const blank = () => ({ outlet_id: '', business_date: today(), shift_code: 'SHIFT-1', pic_name: '', due_at: `${today()}T23:59`, priority: 'normal' as ShiftControl['priority'], checklist: { handover_complete: false, stock_count_complete: false, payment_channels_ready: false, closing_matched: false }, issue_summary: '' });

export default function CellularShiftControlPage() {
  const { user } = useAuth(); const role = user?.role ?? ''; const qc = useQueryClient();
  const [month, setMonth] = useState(today().slice(0, 7)); const [search, setSearch] = useState(''); const [showForm, setShowForm] = useState(false); const [form, setForm] = useState(blank); const [note, setNote] = useState<Record<string, string>>({});
  const controls = useQuery({ queryKey: ['cellular', 'shift-controls', month], queryFn: () => cellularApi.shiftControls(month) });
  const outlets = useQuery({ queryKey: ['cellular', 'outlets'], queryFn: cellularApi.outlets });
  const refresh = async () => qc.invalidateQueries({ queryKey: ['cellular', 'shift-controls'] });
  const save = useMutation({ mutationFn: cellularApi.saveShiftControl, onSuccess: async () => { await refresh(); setShowForm(false); setForm(blank()); } });
  const transition = useMutation({ mutationFn: ({ row, action }: { row: ShiftControl; action: 'submit' | 'review' | 'correction' | 'resolve' | 'escalate' | 'decide' }) => cellularApi.transitionShiftControl(row, action, note[row.id]), onSuccess: refresh });
  const rows = controls.data?.data ?? []; const metrics = useMemo(() => ({ open: rows.filter(row => row.status !== 'resolved').length, overdue: rows.filter(row => row.is_overdue).length, escalated: rows.filter(row => row.status === 'escalated').length, resolved: rows.filter(row => row.status === 'resolved').length }), [rows]);
  const filtered = rows.filter(row => `${row.outlet_name} ${row.pic_name} ${row.shift_code} ${statusLabel[row.status]}`.toLowerCase().includes(search.toLowerCase()));
  if (controls.isLoading || outlets.isLoading) return <LoadingState label="Memuat kontrol shift..." />;
  if (controls.error || outlets.error) return <ErrorState title="Kontrol shift gagal dimuat" description={(controls.error ?? outlets.error)?.message ?? 'Data tidak tersedia.'} onRetry={() => { void controls.refetch(); void outlets.refetch(); }} />;
  const submit = (event: FormEvent) => { event.preventDefault(); save.mutate(form); };
  const act = (row: ShiftControl, action: 'submit' | 'review' | 'correction' | 'resolve' | 'escalate' | 'decide') => transition.mutate({ row, action });

  return <div className="space-y-6 pb-10 animate-fade-in">
    <DivisionPageHeader division="Divisi Cellular" descriptor="Penerimaan Harian · Supervisi" title="Kontrol Shift Outlet" description="Leader melengkapi checklist dan temuan; SPV memeriksa; Head Operasional menyelesaikan atau mengeskalasi risiko ke Manager." actions={role === 'LEADER' ? <Button onClick={() => setShowForm(value => !value)}><Plus className="h-4 w-4"/>Kontrol baru</Button> : undefined} />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Pekerjaan terbuka" value={metrics.open} note="Belum selesai" icon={<ClipboardCheck/>} primary/><Metric label="Lewat tenggat" value={metrics.overdue} note="Butuh tindak lanjut" icon={<Clock3/>} danger={metrics.overdue > 0}/><Metric label="Eskalasi Manager" value={metrics.escalated} note="Risiko perlu keputusan" icon={<AlertTriangle/>} danger={metrics.escalated > 0}/><Metric label="Selesai" value={metrics.resolved} note="Kontrol ditutup" icon={<ShieldCheck/>}/></div>
    {showForm && role === 'LEADER' && <form onSubmit={submit} className="rounded-card border border-line bg-panel p-5 shadow-card"><div className="mb-5"><h2 className="font-bold text-navy">Checklist shift baru</h2><p className="mt-1 text-xs text-subtle">Jika ada poin belum lengkap, tulis temuannya agar jalur supervisi mempunyai konteks.</p></div><div className="grid gap-4 md:grid-cols-3"><Field label="Outlet"><select required className={field} value={form.outlet_id} onChange={e => setForm({...form, outlet_id:e.target.value})}><option value="">Pilih outlet</option>{outlets.data?.data.map(row => <option key={row.id} value={row.id}>{row.name}</option>)}</select></Field><Field label="Tanggal bisnis"><input required type="date" className={field} value={form.business_date} onChange={e => setForm({...form,business_date:e.target.value})}/></Field><Field label="Shift"><input required className={field} value={form.shift_code} onChange={e => setForm({...form,shift_code:e.target.value})}/></Field><Field label="PIC shift"><input required className={field} value={form.pic_name} onChange={e => setForm({...form,pic_name:e.target.value})}/></Field><Field label="Tenggat"><input required type="datetime-local" className={field} value={form.due_at} onChange={e => setForm({...form,due_at:e.target.value})}/></Field><Field label="Prioritas"><select className={field} value={form.priority} onChange={e => setForm({...form,priority:e.target.value as ShiftControl['priority']})}><option value="normal">Normal</option><option value="high">Tinggi</option><option value="critical">Kritis</option></select></Field></div><fieldset className="mt-5 grid gap-3 rounded-input border border-line bg-surface p-4 md:grid-cols-2"><legend className="px-2 text-xs font-bold uppercase tracking-wider text-subtle">Checklist operasional</legend>{(Object.keys(checkLabels) as (keyof ShiftControl['checklist'])[]).map(key => <label key={key} className="flex items-center gap-3 text-sm font-medium text-navy"><input type="checkbox" checked={form.checklist[key]} onChange={e => setForm({...form,checklist:{...form.checklist,[key]:e.target.checked}})}/>{checkLabels[key]}</label>)}</fieldset><Field label="Ringkasan temuan"><textarea className={`${field} mt-5 min-h-24 py-2`} placeholder="Wajib jika ada checklist belum lengkap" value={form.issue_summary} onChange={e => setForm({...form,issue_summary:e.target.value})}/></Field>{save.error && <p role="alert" className="mt-4 rounded-input bg-danger-light p-3 text-sm text-danger">{save.error.message}</p>}<div className="mt-5 flex justify-end"><Button disabled={save.isPending} type="submit">Simpan draf</Button></div></form>}
    <section className="overflow-hidden rounded-card border border-line bg-panel shadow-card"><div className="flex flex-col gap-4 border-b border-line p-5 md:flex-row md:items-center md:justify-between"><div><h2 className="font-bold text-navy">Register kontrol shift</h2><p className="mt-1 text-xs text-subtle">Leader → SPV → Head Operasional → Manager bila diekskalasi</p></div><div className="flex gap-3"><label className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-muted"/><input aria-label="Cari kontrol shift" className={`${field} pl-9`} placeholder="Cari outlet, PIC, status" value={search} onChange={e => setSearch(e.target.value)}/></label><input aria-label="Periode kontrol shift" type="month" className={`${field} w-auto`} value={month} onChange={e => setMonth(e.target.value)}/></div></div><div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-left text-sm"><thead className="bg-surface text-[11px] uppercase tracking-wider text-subtle"><tr><th className="px-5 py-3">Outlet / Shift</th><th>PIC & Tenggat</th><th>Checklist</th><th>Temuan</th><th>Status</th><th className="pr-5">Tindakan</th></tr></thead><tbody className="divide-y divide-line">{filtered.map(row => <tr key={row.id} className="hover:bg-surface/60"><td className="px-5 py-4"><p className="font-semibold text-navy">{row.outlet_name}</p><p className="text-xs text-subtle">{row.business_date} · {row.shift_code}</p></td><td><p className="font-medium text-navy">{row.pic_name}</p><p className={`text-xs ${row.is_overdue ? 'font-semibold text-danger':'text-subtle'}`}>{new Date(row.due_at).toLocaleString('id-ID',{timeZone:'Asia/Jakarta',dateStyle:'medium',timeStyle:'short'})}</p></td><td><p className="font-bold text-navy">{row.completed_checks}/{row.total_checks}</p><div className="mt-1 h-1.5 w-24 overflow-hidden rounded-pill bg-surface"><div className="h-full bg-primary-600" style={{width:`${row.completed_checks/row.total_checks*100}%`}}/></div></td><td className="max-w-52 text-xs text-subtle">{row.issue_summary || 'Tidak ada temuan'}{row.review_note && <p className="mt-1 font-semibold text-danger">{row.review_note}</p>}</td><td><span className={`rounded-pill px-2.5 py-1 text-xs font-bold ${statusClass[row.status]}`}>{statusLabel[row.status]}</span><p className="mt-2 text-[10px] uppercase text-muted">{row.priority}</p></td><td className="pr-5"><Actions row={row} role={role} busy={transition.isPending} note={note[row.id] ?? ''} onNote={value => setNote({...note,[row.id]:value})} act={act}/></td></tr>)}</tbody></table>{!filtered.length && <div className="p-10 text-center"><CheckCircle2 className="mx-auto h-8 w-8 text-muted"/><p className="mt-3 text-sm font-semibold text-navy">Belum ada kontrol shift</p><p className="mt-1 text-xs text-subtle">Data akan muncul setelah Leader membuat checklist.</p></div>}</div>{transition.error && <p role="alert" className="m-5 rounded-input bg-danger-light p-3 text-sm text-danger">{transition.error.message}</p>}</section>
  </div>;
}
function Actions({row,role,busy,note,onNote,act}:{row:ShiftControl;role:string;busy:boolean;note:string;onNote:(value:string)=>void;act:(row:ShiftControl,action:'submit'|'review'|'correction'|'resolve'|'escalate'|'decide')=>void}) { if(role==='LEADER'&&['draft','correction'].includes(row.status)) return <button disabled={busy} className="font-semibold text-primary-700" onClick={()=>act(row,'submit')}>Ajukan ke SPV</button>; if(role==='SPV'&&row.status==='submitted') return <Decision note={note} onNote={onNote} primary="Verifikasi" secondary="Koreksi" primaryAction={()=>act(row,'review')} secondaryAction={()=>act(row,'correction')} busy={busy}/>; if(role==='HEAD_OPS'&&row.status==='reviewed') return <Decision note={note} onNote={onNote} primary="Selesaikan" secondary="Eskalasi" primaryAction={()=>act(row,'resolve')} secondaryAction={()=>act(row,'escalate')} busy={busy}/>; if(role==='MANAGER'&&row.status==='escalated') return <Decision note={note} onNote={onNote} primary="Putuskan selesai" primaryAction={()=>act(row,'decide')} busy={busy} requirePrimaryNote/>; return <span className="text-xs text-muted">Tidak ada tindakan</span>; }
function Decision({note,onNote,primary,secondary,primaryAction,secondaryAction,busy,requirePrimaryNote}:{note:string;onNote:(value:string)=>void;primary:string;secondary?:string;primaryAction:()=>void;secondaryAction?:()=>void;busy:boolean;requirePrimaryNote?:boolean}) { return <div className="flex max-w-72 items-center gap-2"><input aria-label="Catatan tindakan" className="min-h-9 w-32 rounded-input border border-line px-2 text-xs" placeholder="Catatan tindakan" value={note} onChange={e=>onNote(e.target.value)}/><button disabled={busy||(requirePrimaryNote&&note.trim().length<10)} onClick={primaryAction} className="font-semibold text-success">{primary}</button>{secondary&&<button disabled={busy||note.trim().length<10} onClick={secondaryAction} className="font-semibold text-danger">{secondary}</button>}</div>; }
function Metric({label,value,note,icon,primary,danger}:{label:string;value:number;note:string;icon:React.ReactNode;primary?:boolean;danger?:boolean}) { return <article className={`rounded-card border p-5 shadow-card ${primary?'border-primary-600 bg-gradient-to-br from-primary-600 to-primary-800 text-white':'border-line bg-panel'}`}><div className="flex items-start justify-between"><div><p className={`text-xs font-semibold uppercase tracking-wider ${primary?'text-primary-100':'text-subtle'}`}>{label}</p><p className={`mt-2 text-2xl font-bold ${primary?'text-white':danger?'text-danger':'text-navy'}`}>{value}</p></div><span className={`flex h-10 w-10 items-center justify-center rounded-input ${primary?'bg-white/15':'border border-line bg-surface text-primary-600'}`}>{icon}</span></div><p className={`mt-3 text-xs ${primary?'text-primary-100':'text-subtle'}`}>{note}</p></article>; }
function Field({label,children}:{label:string;children:React.ReactNode}) { return <label className="text-xs font-semibold text-subtle">{label}<span className="mt-1.5 block">{children}</span></label>; }
