import { FormEvent, useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowDownToLine, BadgeCheck, Banknote, CheckCircle2, Clock3, Plus, Search, WalletCards } from 'lucide-react';
import { DivisionPageHeader } from '../../../components/ui/DivisionPageHeader';
import { Button } from '../../../components/ui/Button';
import { ErrorState, LoadingState } from '../../../components/states';
import { useAuth } from '../../../session/AuthContext';
import { cellularApi, type Settlement, type SettlementSource } from '../api';

const jakartaToday = () => new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Jakarta', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date());
const money = (value: string | number) => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(Number(value));
const field = 'min-h-10 w-full rounded-input border border-line bg-panel px-3 text-sm text-navy outline-none focus:border-primary-500 focus:ring-2 focus:ring-primary-100';
const channelLabel = { cash: 'Tunai', qris: 'QRIS', edc: 'EDC', transfer: 'Transfer' } as const;
const statusLabel: Record<Settlement['status'], string> = { draft: 'Draf Finance', submitted: 'Menunggu Accounting', reconciled: 'Terekonsiliasi', correction: 'Perlu Koreksi' };
const statusClass: Record<Settlement['status'], string> = { draft: 'bg-surface text-subtle', submitted: 'bg-warning-light text-warning-dark', reconciled: 'bg-success-light text-success', correction: 'bg-danger-light text-danger' };

type Form = { id?: string; version?: number; daily_closing_id: string; channel: SettlementSource['channel']; settlement_date: string; gross: string; fee: string; destination: string; reference: string };
const emptyForm = (): Form => ({ daily_closing_id: '', channel: 'cash', settlement_date: jakartaToday(), gross: '', fee: '0', destination: '', reference: '' });

export default function CellularSettlementPage() {
  const { user } = useAuth(); const qc = useQueryClient(); const role = user?.role ?? '';
  const [month, setMonth] = useState(jakartaToday().slice(0, 7)); const [search, setSearch] = useState(''); const [tab, setTab] = useState<'reconciliation' | 'register'>('reconciliation');
  const [showForm, setShowForm] = useState(false); const [form, setForm] = useState<Form>(emptyForm); const [note, setNote] = useState<Record<string, string>>({});
  const sources = useQuery({ queryKey: ['cellular', 'settlement-sources', month], queryFn: () => cellularApi.settlementSources(month) });
  const settlements = useQuery({ queryKey: ['cellular', 'settlements', month], queryFn: () => cellularApi.settlements(month) });
  const refresh = async () => { await Promise.all([qc.invalidateQueries({ queryKey: ['cellular', 'settlement-sources'] }), qc.invalidateQueries({ queryKey: ['cellular', 'settlements'] })]); };
  const save = useMutation({ mutationFn: cellularApi.saveSettlement, onSuccess: async () => { await refresh(); setShowForm(false); setForm(emptyForm()); setTab('register'); } });
  const transition = useMutation({ mutationFn: ({ row, action }: { row: Settlement; action: 'submit' | 'reconcile' | 'correction' }) => cellularApi.transitionSettlement(row, action, note[row.id]), onSuccess: refresh });
  const sourceRows = sources.data?.data ?? []; const settlementRows = settlements.data?.data ?? [];
  const metrics = useMemo(() => ({ expected: sourceRows.reduce((sum, row) => sum + Number(row.expected), 0), reconciled: sourceRows.reduce((sum, row) => sum + Number(row.reconciled), 0), remaining: sourceRows.reduce((sum, row) => sum + Number(row.remaining), 0), pending: settlementRows.filter(row => row.status === 'submitted').length, fees: settlementRows.filter(row => row.status === 'reconciled').reduce((sum, row) => sum + Number(row.fee), 0) }), [sourceRows, settlementRows]);
  const matchingSources = sourceRows.filter(row => `${row.outlet_name} ${row.business_date} ${row.shift_code} ${channelLabel[row.channel]}`.toLowerCase().includes(search.toLowerCase()));
  const matchingSettlements = settlementRows.filter(row => `${row.outlet_name} ${row.reference} ${row.destination} ${statusLabel[row.status]}`.toLowerCase().includes(search.toLowerCase()));
  if (sources.isLoading || settlements.isLoading) return <LoadingState label="Memuat settlement kanal..." />;
  if (sources.error || settlements.error) return <ErrorState title="Settlement gagal dimuat" description={(sources.error ?? settlements.error)?.message ?? 'Data tidak tersedia.'} onRetry={() => { void sources.refetch(); void settlements.refetch(); }} />;
  const chooseSource = (row: SettlementSource) => { setForm({ daily_closing_id: row.daily_closing_id, channel: row.channel, settlement_date: jakartaToday(), gross: row.remaining, fee: '0', destination: '', reference: '' }); setShowForm(true); };
  const edit = (row: Settlement) => { setForm({ id: row.id, version: row.version, daily_closing_id: row.daily_closing_id, channel: row.channel, settlement_date: row.settlement_date, gross: row.gross, fee: row.fee, destination: row.destination, reference: row.reference }); setShowForm(true); };
  const submit = (event: FormEvent) => { event.preventDefault(); save.mutate(form); };

  return <div className="space-y-6 pb-10 animate-fade-in">
    <DivisionPageHeader division="Divisi Cellular" descriptor="Tagihan & Pembayaran · Settlement" title="Settlement Kanal Pembayaran" description="Pantau nilai yang seharusnya diterima, catat dana masuk Finance, lalu rekonsiliasi oleh Accounting dengan jejak pemeriksaan yang utuh." actions={role === 'FINANCE' ? <Button onClick={() => { setForm(emptyForm()); setShowForm(true); }}><Plus className="h-4 w-4" />Catat settlement</Button> : undefined} />

    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">
      <Metric label="Hak penerimaan" value={money(metrics.expected)} note={`${sourceRows.length} kanal dari closing disetujui`} icon={<WalletCards />} primary />
      <Metric label="Terekonsiliasi" value={money(metrics.reconciled)} note="Sudah diperiksa Accounting" icon={<BadgeCheck />} />
      <Metric label="Belum diterima" value={money(metrics.remaining)} note="Sisa berdasarkan closing" icon={<ArrowDownToLine />} danger={metrics.remaining > 0} />
      <Metric label="Antrean verifikasi" value={metrics.pending} note="Menunggu Accounting" icon={<Clock3 />} />
      <Metric label="Biaya kanal" value={money(metrics.fees)} note="Dari settlement terverifikasi" icon={<Banknote />} />
    </div>

    {showForm && role === 'FINANCE' && <form onSubmit={submit} className="rounded-card border border-line bg-panel p-5 shadow-card">
      <div className="mb-5 flex items-start justify-between"><div><h2 className="font-bold text-navy">{form.id ? 'Perbaiki settlement' : 'Catat dana masuk'}</h2><p className="mt-1 text-xs text-subtle">Pilih kanal dari closing yang disetujui. Nilai neto dihitung otomatis dari bruto dikurangi biaya.</p></div><button type="button" className="text-sm text-subtle" onClick={() => setShowForm(false)}>Tutup</button></div>
      <div className="grid gap-4 md:grid-cols-3">
        <Field label="Sumber closing & kanal"><select required disabled={Boolean(form.id)} className={field} value={`${form.daily_closing_id}|${form.channel}`} onChange={e => { const [daily_closing_id, channel] = e.target.value.split('|') as [string, SettlementSource['channel']]; const row = sourceRows.find(item => item.daily_closing_id === daily_closing_id && item.channel === channel); setForm({ ...form, daily_closing_id, channel, gross: row?.remaining ?? '' }); }}><option value="|cash">Pilih closing</option>{sourceRows.filter(row => Number(row.remaining) > 0).map(row => <option key={`${row.daily_closing_id}-${row.channel}`} value={`${row.daily_closing_id}|${row.channel}`}>{row.business_date} · {row.outlet_name} · {channelLabel[row.channel]} · sisa {money(row.remaining)}</option>)}</select></Field>
        <Field label="Tanggal dana diterima"><input required type="date" max={jakartaToday()} className={field} value={form.settlement_date} onChange={e => setForm({ ...form, settlement_date: e.target.value })} /></Field>
        <Field label="Tujuan bank / kas"><input required className={field} placeholder="Contoh: BCA Operasional" value={form.destination} onChange={e => setForm({ ...form, destination: e.target.value })} /></Field>
        <Field label="Nilai bruto"><input required inputMode="decimal" pattern="\d{1,12}(\.\d{1,2})?" className={field} value={form.gross} onChange={e => setForm({ ...form, gross: e.target.value })} /></Field>
        <Field label="Biaya kanal"><input required inputMode="decimal" pattern="\d{1,12}(\.\d{1,2})?" className={field} value={form.fee} onChange={e => setForm({ ...form, fee: e.target.value })} /></Field>
        <Field label="Referensi bank / batch"><input required className={field} placeholder="Contoh: QRIS-SET-001" value={form.reference} onChange={e => setForm({ ...form, reference: e.target.value })} /></Field>
      </div>
      <div className="mt-4 rounded-input border border-primary-100 bg-primary-50 p-3 text-sm text-primary-800"><span className="font-semibold">Dana neto:</span> {money(Math.max(0, Number(form.gross || 0) - Number(form.fee || 0)))}</div>
      {save.error && <p role="alert" className="mt-4 rounded-input bg-danger-light p-3 text-sm text-danger">{save.error.message}</p>}
      <div className="mt-5 flex justify-end"><Button disabled={save.isPending} type="submit">{save.isPending ? 'Menyimpan...' : 'Simpan draf'}</Button></div>
    </form>}

    <section className="overflow-hidden rounded-card border border-line bg-panel shadow-card">
      <div className="flex flex-col gap-4 border-b border-line p-5 lg:flex-row lg:items-center lg:justify-between">
        <div><h2 className="font-bold text-navy">Kontrol penerimaan kanal</h2><p className="mt-1 text-xs text-subtle">Closing disetujui → Finance mencatat dana → Accounting merekonsiliasi</p></div>
        <div className="flex flex-wrap gap-2"><button onClick={() => setTab('reconciliation')} className={`rounded-input px-3 py-2 text-xs font-semibold ${tab === 'reconciliation' ? 'bg-primary-700 text-white' : 'bg-surface text-subtle'}`}>Rekonsiliasi kanal</button><button onClick={() => setTab('register')} className={`rounded-input px-3 py-2 text-xs font-semibold ${tab === 'register' ? 'bg-primary-700 text-white' : 'bg-surface text-subtle'}`}>Register settlement</button><label className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-muted"/><input aria-label="Cari settlement" className={`${field} pl-9`} placeholder="Cari outlet atau referensi" value={search} onChange={e => setSearch(e.target.value)} /></label><input aria-label="Periode settlement" type="month" className={`${field} w-auto`} value={month} onChange={e => setMonth(e.target.value)} /></div>
      </div>
      {tab === 'reconciliation' ? <ReconciliationTable rows={matchingSources} finance={role === 'FINANCE'} choose={chooseSource} /> : <SettlementTable rows={matchingSettlements} role={role} busy={transition.isPending} note={note} setNote={setNote} edit={edit} act={(row, action) => transition.mutate({ row, action })} />}
      {transition.error && <p role="alert" className="m-5 rounded-input bg-danger-light p-3 text-sm text-danger">{transition.error.message}</p>}
    </section>
  </div>;
}

function ReconciliationTable({ rows, finance, choose }: { rows: SettlementSource[]; finance: boolean; choose: (row: SettlementSource) => void }) { return <div className="overflow-x-auto"><table className="w-full min-w-[930px] text-left text-sm"><thead className="bg-surface text-[11px] uppercase tracking-wider text-subtle"><tr><th className="px-5 py-3">Closing</th><th>Kanal</th><th>Hak penerimaan</th><th>Diajukan</th><th>Terekonsiliasi</th><th>Sisa</th><th className="pr-5">Tindakan</th></tr></thead><tbody className="divide-y divide-line">{rows.map(row => <tr key={`${row.daily_closing_id}-${row.channel}`} className="hover:bg-surface/60"><td className="px-5 py-4"><p className="font-semibold text-navy">{row.outlet_name}</p><p className="text-xs text-subtle">{row.business_date} · {row.shift_code}</p></td><td><span className="rounded-pill bg-primary-50 px-2.5 py-1 text-xs font-bold text-primary-700">{channelLabel[row.channel]}</span></td><td className="font-semibold tabular-nums text-navy">{money(row.expected)}</td><td className="tabular-nums text-subtle">{money(row.submitted)}</td><td className="font-semibold tabular-nums text-success">{money(row.reconciled)}</td><td className={`font-bold tabular-nums ${Number(row.remaining) ? 'text-danger' : 'text-success'}`}>{money(row.remaining)}</td><td className="pr-5">{finance && Number(row.remaining) > 0 ? <button onClick={() => choose(row)} className="font-semibold text-primary-700">Catat dana</button> : <span className="text-xs text-muted">{Number(row.remaining) ? 'Menunggu Finance' : 'Selesai'}</span>}</td></tr>)}</tbody></table>{!rows.length && <Empty text="Belum ada closing disetujui pada periode ini." />}</div>; }
function SettlementTable({ rows, role, busy, note, setNote, edit, act }: { rows: Settlement[]; role: string; busy: boolean; note: Record<string, string>; setNote: (value: Record<string, string>) => void; edit: (row: Settlement) => void; act: (row: Settlement, action: 'submit' | 'reconcile' | 'correction') => void }) { return <div className="overflow-x-auto"><table className="w-full min-w-[1120px] text-left text-sm"><thead className="bg-surface text-[11px] uppercase tracking-wider text-subtle"><tr><th className="px-5 py-3">Settlement</th><th>Closing</th><th>Bruto / Biaya / Neto</th><th>Tujuan</th><th>Status</th><th className="pr-5">Tindakan</th></tr></thead><tbody className="divide-y divide-line">{rows.map(row => <tr key={row.id} className="hover:bg-surface/60"><td className="px-5 py-4"><p className="font-semibold text-navy">{row.reference}</p><p className="text-xs text-subtle">{row.settlement_date} · {channelLabel[row.channel]}</p></td><td><p className="font-medium text-navy">{row.outlet_name}</p><p className="text-xs text-subtle">{row.business_date} · {row.shift_code}</p></td><td className="text-xs leading-5 text-subtle">Bruto <strong className="text-navy">{money(row.gross)}</strong><br/>Biaya {money(row.fee)} · Neto {money(row.net)}</td><td className="text-subtle">{row.destination}</td><td><span className={`rounded-pill px-2.5 py-1 text-xs font-bold ${statusClass[row.status]}`}>{statusLabel[row.status]}</span>{row.review_note && <p className="mt-2 max-w-52 text-xs text-danger">{row.review_note}</p>}</td><td className="pr-5"><Actions row={row} role={role} busy={busy} note={note[row.id] ?? ''} onNote={value => setNote({ ...note, [row.id]: value })} edit={edit} act={act} /></td></tr>)}</tbody></table>{!rows.length && <Empty text="Belum ada settlement pada periode ini." />}</div>; }
function Actions({ row, role, busy, note, onNote, edit, act }: { row: Settlement; role: string; busy: boolean; note: string; onNote: (value: string) => void; edit: (row: Settlement) => void; act: (row: Settlement, action: 'submit' | 'reconcile' | 'correction') => void }) { if (role === 'FINANCE' && ['draft', 'correction'].includes(row.status)) return <div className="flex gap-3"><button disabled={busy} onClick={() => edit(row)} className="font-semibold text-subtle">Ubah</button><button disabled={busy} onClick={() => act(row, 'submit')} className="font-semibold text-primary-700">Ajukan</button></div>; if (role === 'ACCOUNTING' && row.status === 'submitted') return <div className="flex max-w-72 items-center gap-2"><input aria-label={`Catatan ${row.id}`} className="min-h-9 w-32 rounded-input border border-line px-2 text-xs" placeholder="Alasan koreksi" value={note} onChange={e => onNote(e.target.value)} /><button disabled={busy} onClick={() => act(row, 'reconcile')} className="font-semibold text-success">Rekonsiliasi</button><button disabled={busy || note.trim().length < 10} onClick={() => act(row, 'correction')} className="font-semibold text-danger">Koreksi</button></div>; return <span className="text-xs text-muted">Tidak ada tindakan</span>; }
function Metric({ label, value, note, icon, primary, danger }: { label: string; value: string | number; note: string; icon: React.ReactNode; primary?: boolean; danger?: boolean }) { return <article className={`rounded-card border p-5 shadow-card ${primary ? 'border-primary-600 bg-gradient-to-br from-primary-600 to-primary-800 text-white' : 'border-line bg-panel'}`}><div className="flex items-start justify-between"><div><p className={`text-xs font-semibold uppercase tracking-wider ${primary ? 'text-primary-100' : 'text-subtle'}`}>{label}</p><p className={`mt-2 text-xl font-bold ${primary ? 'text-white' : danger ? 'text-danger' : 'text-navy'}`}>{value}</p></div><span className={`flex h-10 w-10 items-center justify-center rounded-input ${primary ? 'bg-white/15' : 'border border-line bg-surface text-primary-600'}`}>{icon}</span></div><p className={`mt-3 text-xs ${primary ? 'text-primary-100' : 'text-subtle'}`}>{note}</p></article>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="text-xs font-semibold text-subtle">{label}<span className="mt-1.5 block">{children}</span></label>; }
function Empty({ text }: { text: string }) { return <div className="p-10 text-center"><CheckCircle2 className="mx-auto h-8 w-8 text-muted"/><p className="mt-3 text-sm font-semibold text-navy">{text}</p><p className="mt-1 text-xs text-subtle">Data akan muncul setelah alur sebelumnya selesai.</p></div>; }
