import { useMemo, useState, type FormEvent, type ReactNode } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { cellularApi, type Movement, type MovementFilters, type Sale } from '../api';
import { useAuth } from '../../../session/AuthContext';
import { hasCapability } from '../../../session/capability';
import { DivisionPageHeader } from '../../../components/ui/DivisionPageHeader';
import { useLocation, useNavigate } from 'react-router-dom';
import { ArrowDownToLine, ArrowUpFromLine, Boxes, Eye, PackageX, Plus, Search, X } from 'lucide-react';
import { KPICard, KPICardGrid } from '../../../components/ui/primitives';
import { Button } from '../../../components/ui/Button';
import { EmptyState } from '../../../components/states';

const today = () => new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Jakarta', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date());
const fieldClass = 'mt-1 w-full rounded-lg border border-line bg-white dark:bg-slate-900 dark:text-slate-100 p-2 text-sm';
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="block text-sm font-medium text-slate-700 dark:text-slate-300">{label}{children}</label>; }

export default function CellularOperationsPage() {
  const { user } = useAuth();
  const can = (cap: string) => !!user && hasCapability(user.role, cap, user.divisionCode);
  const client = useQueryClient();
  const location = useLocation();
  const navigate = useNavigate();
  const tab: 'catalog' | 'stock' | 'sales' = location.pathname.endsWith('/penjualan') ? 'sales' : location.pathname.endsWith('/persediaan') ? 'stock' : 'catalog';
  const [month, setMonth] = useState(today().slice(0, 7));
  const [notice, setNotice] = useState('');
  const [stockFormOpen, setStockFormOpen] = useState(false);
  const [movementDetail, setMovementDetail] = useState<Movement | null>(null);
  const [movementFilters, setMovementFilters] = useState({ month: today().slice(0, 7), outlet_id: '', product_id: '', kind: '', direction: '', q: '' });
  const [product, setProduct] = useState({ sku: '', name: '', kind: 'SIM_CARD', provider: '', variant: '' });
  const [adjustment, setAdjustment] = useState({ product_id: '', outlet_id: '', quantity_delta: '', reference: '', reason: '' });
  const [sale, setSale] = useState({ product_id: '', outlet_id: '', business_date: today(), quantity: '', unit_price: '', reference: '' });
  const [voiding, setVoiding] = useState<Sale | null>(null);
  const [voidReason, setVoidReason] = useState('');
  const products = useQuery({ queryKey: ['cellular', 'products'], queryFn: cellularApi.products, enabled: can('view:cellular') });
  const outlets = useQuery({ queryKey: ['cellular', 'outlets'], queryFn: cellularApi.outlets, enabled: can('view:cellular') });
  const stock = useQuery({ queryKey: ['cellular', 'stock'], queryFn: cellularApi.stock, enabled: can('view:cellular') });
  const movementParams = useMemo(() => Object.fromEntries(Object.entries(movementFilters).filter(([, value]) => value)), [movementFilters]);
  const movements = useQuery({ queryKey: ['cellular', 'movements', movementParams], queryFn: () => cellularApi.movementRegister(movementParams as MovementFilters), enabled: can('view:cellular') });
  const sales = useQuery({ queryKey: ['cellular', 'sales', month], queryFn: () => cellularApi.sales(month), enabled: can('view:cellular_sales') && /^\d{4}-\d{2}$/.test(month) });
  const mutation = useMutation({ mutationFn: async (action: 'product' | 'stock' | 'sale' | 'void') => {
    if (action === 'product') await cellularApi.createProduct({ ...product, provider: product.provider || null, variant: product.variant || null });
    if (action === 'stock') await cellularApi.adjust({ ...adjustment, quantity_delta: Number(adjustment.quantity_delta) });
    if (action === 'sale') await cellularApi.sell({ ...sale, quantity: Number(sale.quantity) });
    if (action === 'void' && voiding) await cellularApi.voidSale(voiding, voidReason);
    return action;
  }, onSuccess: action => {
    void client.invalidateQueries({ queryKey: ['cellular'] });
    setNotice(action === 'void' ? 'Penjualan dibatalkan dan jumlah stok dikembalikan.' : 'Data berhasil disimpan.');
    if (action === 'product') setProduct({ sku: '', name: '', kind: 'SIM_CARD', provider: '', variant: '' });
    if (action === 'stock') { setAdjustment(a => ({ ...a, quantity_delta: '', reference: '', reason: '' })); setStockFormOpen(false); }
    if (action === 'sale') { setMonth(sale.business_date.slice(0, 7)); setSale(s => ({ ...s, quantity: '', unit_price: '', reference: '' })); }
    if (action === 'void') { setVoiding(null); setVoidReason(''); }
  } });
  const submit = (action: 'product' | 'stock' | 'sale' | 'void') => (e: FormEvent) => { e.preventDefault(); if (mutation.isPending) return; setNotice(''); mutation.mutate(action); };
  const busy = mutation.isPending;
  const outletName = (id: string) => outlets.data?.data.find(o => o.id === id)?.name ?? 'Outlet tidak tersedia';
  const stockRows = stock.data?.data ?? [];
  const movementRows = movements.data?.data ?? [];
  const stockMetrics = useMemo(() => ({
    units: stockRows.reduce((sum, row) => sum + row.quantity, 0),
    critical: stockRows.filter(row => row.quantity <= 5).length,
    incoming: movementRows.filter(row => row.quantity_delta > 0).reduce((sum, row) => sum + row.quantity_delta, 0),
    outgoing: Math.abs(movementRows.filter(row => row.quantity_delta < 0).reduce((sum, row) => sum + row.quantity_delta, 0)),
  }), [movementRows, stockRows]);
  const choices = (value: string, set: (value: string) => void, kind: 'product' | 'outlet') => <select required className={fieldClass} value={value} onChange={e => set(e.target.value)}><option value="">Pilih {kind === 'product' ? 'produk' : 'outlet'}</option>{kind === 'product' ? products.data?.data.map(p => <option key={p.id} value={p.id}>{p.sku} — {p.name}</option>) : outlets.data?.data.map(o => <option key={o.id} value={o.id}>{o.name}</option>)}</select>;
  const button = (label: string) => <button className="rounded-lg bg-primary-600 px-4 py-2 text-sm text-white disabled:opacity-50" disabled={busy}>{busy ? 'Menyimpan...' : label}</button>;
  const queries = [products, outlets, stock, movements, ...(can('view:cellular_sales') ? [sales] : [])];
  const pageCopy = tab === 'catalog'
    ? { descriptor: 'Produk · Master Katalog', title: 'Katalog Produk Cellular', description: 'Kelola kartu perdana, provider, kuota, dan aksesori sebagai master transaksi dan persediaan.' }
    : tab === 'stock'
      ? { descriptor: 'Persediaan · Stok & Mutasi', title: 'Stok dan Mutasi Cellular', description: 'Pantau saldo barang per outlet serta catat penerimaan, transfer, dan koreksi jumlah barang.' }
      : { descriptor: 'Transaksi · Penjualan Outlet', title: 'Penjualan Cellular', description: 'Catat dan telusuri penjualan manual kartu perdana serta aksesori per outlet dan periode.' };
  const openTab = (next: 'catalog' | 'stock' | 'sales') => {
    setVoiding(null); setVoidReason(''); setStockFormOpen(false); setMovementDetail(null); mutation.reset(); setNotice('');
    navigate(next === 'catalog' ? '/cellular/produk' : next === 'stock' ? '/cellular/persediaan' : '/cellular/penjualan');
  };
  if (!can('view:cellular')) return <p role="alert" className="p-6">Akses operasional Cellular tidak tersedia untuk akun ini.</p>;
  return <div className="min-w-0 space-y-6 pb-10">
    <DivisionPageHeader division="Divisi Cellular" descriptor={pageCopy.descriptor} title={pageCopy.title} description={pageCopy.description} />
    <nav className="flex flex-wrap gap-1 border-b border-line" aria-label="Bagian operasional Cellular">{(['catalog', 'stock', ...(can('view:cellular_sales') ? ['sales'] : [])] as const).map(t => <button key={t} type="button" disabled={busy} aria-pressed={tab === t} className={`min-h-11 border-b-2 px-4 text-sm font-semibold transition-colors ${tab === t ? 'border-primary-600 text-primary-700 dark:text-primary-300' : 'border-transparent text-subtle hover:text-navy'}`} onClick={() => openTab(t as typeof tab)}>{t === 'catalog' ? 'Katalog produk' : t === 'stock' ? 'Stok & mutasi' : 'Penjualan'}</button>)}</nav>
    {queries.some(q => q.isLoading) && <p role="status">Memuat data...</p>}
    {queries.filter(q => q.error).map((q, i) => <div key={i} role="alert" className="rounded-lg bg-red-50 p-3 text-red-700">{q.error?.message}<button type="button" className="ml-3 underline" onClick={() => void q.refetch()}>Coba lagi</button></div>)}
    {mutation.error && <p role="alert" className="rounded-lg bg-red-50 p-3 text-red-700">{mutation.error.message}</p>}
    {notice && <p role="status" className="rounded-lg bg-green-50 p-3 text-green-800">{notice}</p>}
    {tab === 'catalog' && <>
      {can('manage:cellular_catalog') && <fieldset disabled={busy} className="contents"><form aria-label="Tambah produk" onSubmit={submit('product')} className="grid gap-3 rounded-xl border border-line bg-white dark:bg-slate-900 dark:text-slate-100 p-5 md:grid-cols-2"><h2 className="font-semibold md:col-span-2">Tambah produk</h2>
        <Field label="SKU"><input required maxLength={50} pattern="[A-Za-z0-9_-]+" className={fieldClass} value={product.sku} onChange={e => setProduct({ ...product, sku: e.target.value })} /></Field>
        <Field label="Nama produk"><input required maxLength={255} className={fieldClass} value={product.name} onChange={e => setProduct({ ...product, name: e.target.value })} /></Field>
        <Field label="Jenis"><select className={fieldClass} value={product.kind} onChange={e => setProduct({ ...product, kind: e.target.value })}><option value="SIM_CARD">Kartu perdana</option><option value="ACCESSORY">Aksesori</option></select></Field>
        <Field label="Provider (opsional)"><input maxLength={100} className={fieldClass} value={product.provider} onChange={e => setProduct({ ...product, provider: e.target.value })} /></Field>
        <Field label="Varian / kuota (opsional)"><input maxLength={255} className={fieldClass} value={product.variant} onChange={e => setProduct({ ...product, variant: e.target.value })} /></Field><div className="self-end">{button('Simpan produk')}</div>
      </form></fieldset>}
      <section className="max-w-full overflow-x-auto rounded-xl border border-line bg-white dark:bg-slate-900 dark:text-slate-100 p-5"><h2 className="mb-3 font-semibold">Katalog produk</h2><p className="mb-3 text-xs text-slate-500 dark:text-slate-400">Menampilkan maksimal 500 produk menurut SKU.</p><table className="w-full min-w-[640px] text-left text-sm"><thead><tr><th>SKU</th><th>Produk</th><th>Jenis</th><th>Provider</th><th>Varian / kuota</th></tr></thead><tbody>{products.data?.data.map(p => <tr key={p.id} className="border-t border-line"><td className="py-3">{p.sku}</td><td>{p.name}</td><td>{p.kind === 'SIM_CARD' ? 'Kartu perdana' : 'Aksesori'}</td><td>{p.provider || '—'}</td><td>{p.variant || '—'}</td></tr>)}</tbody></table>{products.isSuccess && products.data.data.length === 0 && <p className="mt-4 text-slate-500 dark:text-slate-400">Belum ada produk.</p>}</section>
    </>}
    {tab === 'stock' && <>
      <div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-primary-700 dark:text-primary-300">Kontrol kuantitas</p><h2 className="mt-1 text-xl font-bold text-navy">Buku Persediaan</h2><p className="mt-1 text-sm text-subtle">Telusuri setiap perubahan saldo ke transaksi atau bukti sumbernya.</p></div>{can('write:cellular_stock') && <Button onClick={() => setStockFormOpen(true)}><Plus className="mr-2 h-4 w-4" />Catat mutasi</Button>}</div>
      <KPICardGrid columns={4}>
        <KPICard variant="gradient" label="Saldo unit" value={stockMetrics.units.toLocaleString('id-ID')} note={`${stockRows.length} kombinasi produk dan outlet`} icon={<Boxes />} />
        <KPICard variant={stockMetrics.critical ? 'outlined' : 'default'} label="Stok kritis" value={stockMetrics.critical.toLocaleString('id-ID')} note="Saldo lima unit atau kurang; batas sementara" icon={<PackageX />} />
        <KPICard label="Barang masuk" value={stockMetrics.incoming.toLocaleString('id-ID')} note={`Periode ${movementFilters.month || 'seluruh data'}`} icon={<ArrowDownToLine />} />
        <KPICard label="Barang keluar" value={stockMetrics.outgoing.toLocaleString('id-ID')} note={`Periode ${movementFilters.month || 'seluruh data'}`} icon={<ArrowUpFromLine />} />
      </KPICardGrid>
      <section className="rounded-card-lg border border-line bg-panel p-5 shadow-card"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-6"><label className="text-xs font-semibold text-subtle xl:col-span-2">Cari bukti atau produk<div className="relative mt-1"><Search className="absolute left-3 top-2.5 h-4 w-4 text-muted" /><input aria-label="Cari bukti atau produk" maxLength={100} className={`${fieldClass} mt-0 pl-9`} value={movementFilters.q} onChange={e => setMovementFilters({ ...movementFilters, q: e.target.value })} placeholder="SKU, nama, referensi, alasan" /></div></label><Field label="Periode posting"><input type="month" className={fieldClass} value={movementFilters.month} onChange={e => setMovementFilters({ ...movementFilters, month: e.target.value })} /></Field><Field label="Outlet"><select className={fieldClass} value={movementFilters.outlet_id} onChange={e => setMovementFilters({ ...movementFilters, outlet_id: e.target.value })}><option value="">Semua outlet</option>{outlets.data?.data.map(o => <option key={o.id} value={o.id}>{o.name}</option>)}</select></Field><Field label="Sumber"><select className={fieldClass} value={movementFilters.kind} onChange={e => setMovementFilters({ ...movementFilters, kind: e.target.value })}><option value="">Semua sumber</option><option value="ADJUSTMENT">Mutasi manual</option><option value="SALE">Penjualan</option><option value="VOID">Pembatalan</option></select></Field><Field label="Arah"><select className={fieldClass} value={movementFilters.direction} onChange={e => setMovementFilters({ ...movementFilters, direction: e.target.value })}><option value="">Masuk dan keluar</option><option value="IN">Barang masuk</option><option value="OUT">Barang keluar</option></select></Field></div><div className="mt-3 flex justify-end"><button type="button" className="text-xs font-semibold text-primary-700 underline dark:text-primary-300" onClick={() => setMovementFilters({ month: today().slice(0, 7), outlet_id: '', product_id: '', kind: '', direction: '', q: '' })}>Reset filter</button></div></section>
      <section className="overflow-hidden rounded-card-lg border border-line bg-panel shadow-card"><div className="flex flex-wrap items-start justify-between gap-3 border-b border-line p-5"><div><h2 className="font-bold text-navy">Register mutasi</h2><p className="mt-1 text-xs text-subtle">{movementRows.length} transaksi ditemukan · maksimal 250 transaksi per pencarian</p></div><span className="rounded-pill bg-primary-50 px-3 py-1 text-xs font-bold text-primary-700 dark:bg-primary-950 dark:text-primary-200">Jejak sumber aktif</span></div>{movementRows.length ? <div className="overflow-x-auto"><table className="w-full min-w-[960px] text-left text-sm"><thead className="bg-surface text-xs uppercase tracking-wide text-subtle"><tr><th className="px-5 py-3">Waktu posting</th><th>Produk</th><th>Outlet</th><th>Sumber & bukti</th><th className="text-right">Perubahan</th><th className="text-right">Saldo</th><th className="px-5 text-right">Detail</th></tr></thead><tbody className="divide-y divide-line">{movementRows.map(row => <tr key={row.id} className="transition-colors hover:bg-surface"><td className="px-5 py-4 text-subtle">{new Intl.DateTimeFormat('id-ID', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'Asia/Jakarta' }).format(new Date(row.created_at))}</td><td><strong className="text-navy">{row.sku}</strong><p className="text-xs text-subtle">{row.name}</p></td><td>{outletName(row.outlet_id)}</td><td><span className="rounded-pill border border-line bg-surface px-2 py-1 text-xs font-semibold text-navy">{row.source_document_type ?? 'Bukti sumber'}</span><p className="mt-2 font-medium text-navy">{row.reference ?? '—'}</p></td><td className={`text-right text-base font-bold tabular-nums ${row.quantity_delta > 0 ? 'text-emerald-700 dark:text-emerald-300' : 'text-red-700 dark:text-red-300'}`}>{row.quantity_delta > 0 ? '+' : ''}{row.quantity_delta.toLocaleString('id-ID')}</td><td className="text-right font-bold tabular-nums text-navy">{row.quantity_after.toLocaleString('id-ID')}</td><td className="px-5 text-right"><button type="button" aria-label={`Lihat mutasi ${row.reference ?? row.id}`} className="inline-flex min-h-10 items-center gap-2 font-semibold text-primary-700 underline dark:text-primary-300" onClick={() => setMovementDetail(row)}><Eye className="h-4 w-4" />Lihat</button></td></tr>)}</tbody></table></div> : <div className="p-6"><EmptyState title="Mutasi tidak ditemukan" description="Ubah filter atau catat mutasi persediaan pertama untuk periode ini." /></div>}</section>
      <section className="overflow-hidden rounded-card-lg border border-line bg-panel shadow-card"><div className="border-b border-line p-5"><h2 className="font-bold text-navy">Posisi stok saat ini</h2><p className="mt-1 text-xs text-subtle">Saldo aktual per produk dan outlet. HPP belum dihitung karena metode valuasi belum ditetapkan.</p></div>{stockRows.length ? <div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-surface text-xs uppercase tracking-wide text-subtle"><tr><th className="px-5 py-3">Produk</th><th>Outlet</th><th className="text-right">Saldo</th><th className="px-5">Kondisi</th></tr></thead><tbody className="divide-y divide-line">{stockRows.map(row => <tr key={row.id}><td className="px-5 py-4"><strong className="text-navy">{row.sku}</strong><p className="text-xs text-subtle">{row.name}</p></td><td>{outletName(row.outlet_id)}</td><td className="text-right text-lg font-bold tabular-nums text-navy">{row.quantity.toLocaleString('id-ID')}</td><td className="px-5">{row.quantity <= 5 ? <span className="font-semibold text-red-700 dark:text-red-300">Perlu tindak lanjut</span> : <span className="font-semibold text-emerald-700 dark:text-emerald-300">Tersedia</span>}</td></tr>)}</tbody></table></div> : <div className="p-6"><EmptyState title="Belum ada saldo" description="Saldo terbentuk dari penerimaan, koreksi, atau penjualan yang telah dicatat." /></div>}</section>
      {stockFormOpen && can('write:cellular_stock') && <div role="dialog" aria-modal="true" aria-label="Catat mutasi stok" className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4"><fieldset disabled={busy} className="w-full max-w-2xl"><form aria-label="Catat mutasi stok" onSubmit={submit('stock')} className="grid gap-4 rounded-card-lg border border-line bg-panel p-6 shadow-2xl md:grid-cols-2"><div className="flex items-start justify-between md:col-span-2"><div><p className="text-xs font-bold uppercase tracking-wider text-primary-700 dark:text-primary-300">Persediaan Cellular</p><h2 className="mt-1 text-xl font-bold text-navy">Catat mutasi manual</h2><p className="mt-1 text-sm text-subtle">Gunakan untuk penerimaan, transfer, atau koreksi dengan bukti yang dapat ditelusuri.</p></div><button type="button" aria-label="Tutup form mutasi" onClick={() => setStockFormOpen(false)}><X className="h-5 w-5" /></button></div><Field label="Produk">{choices(adjustment.product_id, v => setAdjustment({ ...adjustment, product_id: v }), 'product')}</Field><Field label="Outlet">{choices(adjustment.outlet_id, v => setAdjustment({ ...adjustment, outlet_id: v }), 'outlet')}</Field><Field label="Perubahan jumlah (+ masuk, − keluar)"><input required type="number" min={-1000000} max={1000000} step={1} className={fieldClass} value={adjustment.quantity_delta} onChange={e => setAdjustment({ ...adjustment, quantity_delta: e.target.value })} /></Field><Field label="Nomor bukti / referensi"><input required maxLength={255} className={fieldClass} value={adjustment.reference} onChange={e => setAdjustment({ ...adjustment, reference: e.target.value })} placeholder="Surat jalan, BA, atau nomor transfer" /></Field><div className="md:col-span-2"><Field label="Alasan mutasi"><textarea required minLength={10} maxLength={2000} className={fieldClass} value={adjustment.reason} onChange={e => setAdjustment({ ...adjustment, reason: e.target.value })} /></Field></div><p className="text-xs text-subtle md:col-span-2">Referensi harus unik untuk produk dan outlet yang sama. Sistem menolak stok negatif dan mencatat audit pelaku.</p><div className="flex gap-2 md:col-span-2"><Button type="submit" disabled={busy}>{busy ? 'Menyimpan...' : 'Simpan mutasi'}</Button><Button type="button" variant="secondary" disabled={busy} onClick={() => setStockFormOpen(false)}>Batal</Button></div></form></fieldset></div>}
      {movementDetail && <div role="dialog" aria-modal="true" aria-label="Detail mutasi persediaan" className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4"><article className="w-full max-w-xl rounded-card-lg border border-line bg-panel p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-primary-700 dark:text-primary-300">Jejak transaksi</p><h2 className="mt-1 text-xl font-bold text-navy">{movementDetail.reference ?? movementDetail.id}</h2><p className="mt-1 text-sm text-subtle">{movementDetail.source_document_type ?? 'Bukti sumber'}</p></div><button type="button" aria-label="Tutup detail mutasi" onClick={() => setMovementDetail(null)}><X className="h-5 w-5" /></button></div><dl className="mt-6 grid gap-4 text-sm sm:grid-cols-2"><div><dt className="text-subtle">Produk</dt><dd className="mt-1 font-semibold text-navy">{movementDetail.sku} · {movementDetail.name}</dd></div><div><dt className="text-subtle">Outlet</dt><dd className="mt-1 font-semibold text-navy">{outletName(movementDetail.outlet_id)}</dd></div><div><dt className="text-subtle">Perubahan</dt><dd className="mt-1 font-semibold text-navy">{movementDetail.quantity_delta > 0 ? '+' : ''}{movementDetail.quantity_delta.toLocaleString('id-ID')} unit</dd></div><div><dt className="text-subtle">Saldo sesudah</dt><dd className="mt-1 font-semibold text-navy">{movementDetail.quantity_after.toLocaleString('id-ID')} unit</dd></div><div className="sm:col-span-2"><dt className="text-subtle">Alasan</dt><dd className="mt-1 rounded-input bg-surface p-3 text-navy">{movementDetail.reason ?? 'Tidak tersedia'}</dd></div><div><dt className="text-subtle">ID dokumen sumber</dt><dd className="mt-1 break-all font-mono text-xs text-navy">{movementDetail.source_document_id ?? 'Bukti eksternal'}</dd></div><div><dt className="text-subtle">ID pelaku</dt><dd className="mt-1 break-all font-mono text-xs text-navy">{movementDetail.actor_id ?? 'Tidak tersedia'}</dd></div></dl></article></div>}
    </>}
    {tab === 'sales' && can('view:cellular_sales') && <>
      {can('write:cellular_sale') && <fieldset disabled={busy} className="contents"><form aria-label="Catat penjualan" onSubmit={submit('sale')} className="grid gap-3 rounded-xl border border-line bg-white dark:bg-slate-900 dark:text-slate-100 p-5 md:grid-cols-2"><h2 className="font-semibold md:col-span-2">Catat penjualan manual</h2><Field label="Produk">{choices(sale.product_id, v => setSale({ ...sale, product_id: v }), 'product')}</Field><Field label="Outlet">{choices(sale.outlet_id, v => setSale({ ...sale, outlet_id: v }), 'outlet')}</Field><Field label="Tanggal penjualan"><input required type="date" max={today()} className={fieldClass} value={sale.business_date} onChange={e => setSale({ ...sale, business_date: e.target.value })} /></Field><Field label="Jumlah terjual"><input required type="number" min={1} max={1000000} step={1} className={fieldClass} value={sale.quantity} onChange={e => setSale({ ...sale, quantity: e.target.value })} /></Field><Field label="Harga per unit (Rp)"><input required inputMode="decimal" pattern="[0-9]{1,12}(\.[0-9]{1,2})?" className={fieldClass} value={sale.unit_price} onChange={e => setSale({ ...sale, unit_price: e.target.value })} /></Field><Field label="Referensi laporan manual"><input required maxLength={255} className={fieldClass} value={sale.reference} onChange={e => setSale({ ...sale, reference: e.target.value })} /></Field><div>{button('Simpan penjualan')}</div></form></fieldset>}
      <Field label="Bulan laporan"><input required type="month" disabled={busy} className={`${fieldClass} max-w-xs`} value={month} onChange={e => { setMonth(e.target.value); setVoiding(null); setVoidReason(''); setNotice(''); mutation.reset(); }} /></Field>
      <section className="max-w-full overflow-x-auto rounded-xl border border-line bg-white dark:bg-slate-900 dark:text-slate-100 p-5"><h2 className="mb-2 font-semibold">Penjualan manual</h2><p className="mb-3 text-xs text-slate-500 dark:text-slate-400">Maksimal 100 catatan terbaru pada bulan terpilih. Belum terhubung otomatis ke jurnal, penerimaan kas, atau omzet Accounting.</p><table className="w-full min-w-[640px] text-left text-sm"><thead><tr><th>Tanggal</th><th>Outlet / produk</th><th>Referensi</th><th>Jumlah</th><th>Harga / total (Rp)</th><th>Status</th>{can('void:cellular_sale') && <th>Aksi</th>}</tr></thead><tbody>{sales.data?.data.map(s => <tr key={s.id} className="border-t border-line"><td className="py-3">{s.business_date}</td><td>{s.outlet_name}<br />{s.product_name}</td><td>{s.source_reference}</td><td>{s.quantity}</td><td>{s.unit_price} / {s.total_amount}</td><td>{s.status === 'posted' ? 'Tercatat' : 'Dibatalkan'}{s.void_reason && <p>{s.void_reason}</p>}</td>{can('void:cellular_sale') && <td>{s.status === 'posted' && <button type="button" aria-label={`Batalkan penjualan ${s.source_reference}`} disabled={busy} className="min-h-10 text-red-700 underline" onClick={() => { setVoiding(s); setVoidReason(''); mutation.reset(); }}>Batalkan</button>}</td>}</tr>)}</tbody></table>{sales.isSuccess && sales.data.data.length === 0 && <p className="mt-4 text-slate-500 dark:text-slate-400">Belum ada penjualan pada bulan ini.</p>}</section>
      {voiding && <fieldset disabled={busy} className="contents"><form aria-label="Batalkan penjualan" onSubmit={submit('void')} className="space-y-3 rounded-xl border border-red-200 bg-white dark:bg-slate-900 dark:text-slate-100 p-5"><h2 className="font-semibold">Batalkan {voiding.source_reference}</h2><p className="text-sm text-slate-600 dark:text-slate-300">Jumlah {voiding.quantity} barang akan dikembalikan ke stok. Pembatalan ini belum mencatat pengembalian uang.</p><Field label="Alasan pembatalan"><textarea required minLength={10} maxLength={2000} className={fieldClass} value={voidReason} onChange={e => setVoidReason(e.target.value)} /></Field>{button('Konfirmasi pembatalan')}<button type="button" disabled={busy} className="ml-3 text-sm underline" onClick={() => setVoiding(null)}>Tutup</button></form></fieldset>}
    </>}
  </div>;
}
