import { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { AlertTriangle, BadgeCheck, Boxes, Calculator, CheckCircle2, Clock3, Search } from 'lucide-react';
import { DivisionPageHeader } from '../../../components/ui/DivisionPageHeader';
import { ErrorState, LoadingState } from '../../../components/states';
import { cellularApi, type DailyClosing } from '../api';

const today = () => new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Jakarta', year: 'numeric', month: '2-digit' }).format(new Date()).slice(0, 7);
const money = (value: number | string) => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(Number(value));
const field = 'min-h-10 rounded-input border border-line bg-panel px-3 text-sm text-navy outline-none focus:border-primary-500 focus:ring-2 focus:ring-primary-100';

export default function CellularAccountingControlPage() {
  const [month, setMonth] = useState(today); const [search, setSearch] = useState('');
  const closings = useQuery({ queryKey: ['cellular','daily-closings',month], queryFn:()=>cellularApi.dailyClosings(month) });
  const sources = useQuery({ queryKey: ['cellular','settlement-sources',month], queryFn:()=>cellularApi.settlementSources(month) });
  const shifts = useQuery({ queryKey: ['cellular','shift-controls',month], queryFn:()=>cellularApi.shiftControls(month) });
  const sales = useQuery({ queryKey: ['cellular','sales',month], queryFn:()=>cellularApi.sales(month) });
  const stock = useQuery({ queryKey: ['cellular','stock'], queryFn:cellularApi.stock });
  const queries=[closings,sources,shifts,sales,stock]; const failure=queries.find(query=>query.error);
  const data=useMemo(()=>{
    const closingRows=closings.data?.data??[]; const sourceRows=sources.data?.data??[]; const saleRows=(sales.data?.data??[]).filter(row=>row.status==='posted'); const shiftRows=shifts.data?.data??[]; const stockRows=stock.data?.data??[];
    const settlementByClosing=new Map<string,{expected:number;reconciled:number;remaining:number}>(); sourceRows.forEach(row=>{const item=settlementByClosing.get(row.daily_closing_id)??{expected:0,reconciled:0,remaining:0};item.expected+=Number(row.expected);item.reconciled+=Number(row.reconciled);item.remaining+=Number(row.remaining);settlementByClosing.set(row.daily_closing_id,item);});
    return {closingRows,sourceRows,saleRows,shiftRows,stockRows,settlementByClosing,gross:saleRows.reduce((sum,row)=>sum+Number(row.total_amount),0),difference:closingRows.reduce((sum,row)=>sum+Number(row.difference),0),remaining:sourceRows.reduce((sum,row)=>sum+Number(row.remaining),0),approved:closingRows.filter(row=>row.status==='approved').length,exceptions:closingRows.filter(row=>row.status==='correction'||Number(row.difference)!==0).length+shiftRows.filter(row=>['correction','escalated'].includes(row.status)).length,lowStock:stockRows.filter(row=>row.quantity<=5).length};
  },[closings.data,sources.data,shifts.data,sales.data,stock.data]);
  if(queries.some(query=>query.isLoading)) return <LoadingState label="Menyusun kontrol Accounting Cellular..."/>;
  if(failure) return <ErrorState title="Kontrol Accounting gagal dimuat" description={failure.error?.message??'Data tidak tersedia.'} onRetry={()=>queries.forEach(query=>void query.refetch())}/>;
  const filtered=data.closingRows.filter(row=>`${row.business_date} ${row.shift_code} ${row.source_reference} ${row.status}`.toLowerCase().includes(search.toLowerCase()));
  return <div className="space-y-6 pb-10 animate-fade-in">
    <DivisionPageHeader division="Divisi Cellular" descriptor="Pembukuan · Kontrol Accounting" title="Kontrol Accounting Cellular" description="Satukan penjualan, closing H+1, settlement kanal, kontrol shift, dan persediaan sebelum data diteruskan ke Accounting pusat." actions={<label className="text-xs font-semibold text-subtle">Periode<input aria-label="Periode kontrol accounting" type="month" className={`${field} mt-1 block`} value={month} onChange={e=>setMonth(e.target.value)}/></label>}/>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Omzet posted" value={money(data.gross)} note={`${data.saleRows.length} transaksi`} icon={<Calculator/>} primary/><Metric label="Closing disetujui" value={`${data.approved}/${data.closingRows.length}`} note="Siap menjadi sumber settlement" icon={<BadgeCheck/>}/><Metric label="Sisa settlement" value={money(data.remaining)} note="Belum terekonsiliasi" icon={<Clock3/>} danger={data.remaining>0}/><Metric label="Pengecualian" value={data.exceptions} note="Selisih, koreksi, atau eskalasi" icon={<AlertTriangle/>} danger={data.exceptions>0}/><Metric label="Stok kritis" value={data.lowStock} note="Saldo lima unit atau kurang" icon={<Boxes/>}/></div>
    <section className="grid gap-4 lg:grid-cols-3"><Readiness title="Paket H+1" value={`${data.approved}/${data.closingRows.length}`} detail="Closing yang telah melewati Admin, Accounting, dan Manager." ready={data.closingRows.length>0&&data.approved===data.closingRows.length}/><Readiness title="Settlement kanal" value={money(data.sourceRows.reduce((sum,row)=>sum+Number(row.reconciled),0))} detail={`Dari hak penerimaan ${money(data.sourceRows.reduce((sum,row)=>sum+Number(row.expected),0))}.`} ready={data.sourceRows.length>0&&data.remaining===0}/><Readiness title="Kontrol operasional" value={`${data.shiftRows.filter(row=>row.status==='resolved').length}/${data.shiftRows.length}`} detail="Shift selesai setelah supervisi dan eskalasi bila diperlukan." ready={data.shiftRows.length>0&&data.shiftRows.every(row=>row.status==='resolved')}/></section>
    <section className="overflow-hidden rounded-card border border-line bg-panel shadow-card"><div className="flex flex-col gap-4 border-b border-line p-5 md:flex-row md:items-center md:justify-between"><div><h2 className="font-bold text-navy">Matriks closing dan settlement</h2><p className="mt-1 text-xs text-subtle">Titik pemeriksaan per tanggal dan shift sebelum penutupan periode.</p></div><label className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-muted"/><input aria-label="Cari closing accounting" className={`${field} pl-9`} placeholder="Cari tanggal, shift, referensi" value={search} onChange={e=>setSearch(e.target.value)}/></label></div><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="bg-surface text-[11px] uppercase tracking-wider text-subtle"><tr><th className="px-5 py-3">Tanggal / Shift</th><th>Omzet Sistem</th><th>Selisih Closing</th><th>Hak Settlement</th><th>Terekonsiliasi</th><th>Sisa</th><th className="pr-5">Kesiapan</th></tr></thead><tbody className="divide-y divide-line">{filtered.map(row=><ClosingRow key={row.id} row={row} settlement={data.settlementByClosing.get(row.id)}/>)}</tbody></table>{!filtered.length&&<div className="p-10 text-center"><CheckCircle2 className="mx-auto h-8 w-8 text-muted"/><p className="mt-3 text-sm font-semibold text-navy">Belum ada closing pada periode ini</p></div>}</div></section>
    <section className="rounded-card border border-warning/30 bg-warning-light p-5 text-warning-dark"><h2 className="font-bold">Batas kebijakan PNL/HPP</h2><p className="mt-2 text-sm leading-6">Kontrol ini menyiapkan sumber yang dapat ditelusuri. Nilai HPP, pengakuan pendapatan, bonus, dan PNL belum dihitung karena kebijakan perusahaan belum ditetapkan. Sistem tidak membuat angka sementara yang dapat disalahartikan sebagai laporan resmi.</p></section>
  </div>;
}
function ClosingRow({row,settlement}:{row:DailyClosing;settlement?:{expected:number;reconciled:number;remaining:number}}){const ready=row.status==='approved'&&Number(row.difference)===0&&(settlement?.remaining??0)===0;return <tr className="hover:bg-surface/60"><td className="px-5 py-4"><p className="font-semibold text-navy">{row.business_date} · {row.shift_code}</p><p className="text-xs text-subtle">{row.source_reference}</p></td><td className="font-semibold tabular-nums text-navy">{money(row.system_sales)}</td><td className={`font-bold tabular-nums ${Number(row.difference)===0?'text-success':'text-danger'}`}>{money(row.difference)}</td><td className="tabular-nums text-subtle">{money(settlement?.expected??0)}</td><td className="font-semibold tabular-nums text-success">{money(settlement?.reconciled??0)}</td><td className={`font-bold tabular-nums ${(settlement?.remaining??0)>0?'text-danger':'text-success'}`}>{money(settlement?.remaining??0)}</td><td className="pr-5"><span className={`rounded-pill px-2.5 py-1 text-xs font-bold ${ready?'bg-success-light text-success':'bg-warning-light text-warning-dark'}`}>{ready?'Siap ditutup':'Perlu tindak lanjut'}</span></td></tr>}
function Readiness({title,value,detail,ready}:{title:string;value:string;detail:string;ready:boolean}){return <article className="rounded-card border border-line bg-panel p-5 shadow-card"><div className="flex items-center justify-between"><p className="text-xs font-bold uppercase tracking-wider text-subtle">{title}</p>{ready?<CheckCircle2 className="h-5 w-5 text-success"/>:<Clock3 className="h-5 w-5 text-warning-dark"/>}</div><p className="mt-3 text-2xl font-bold text-navy">{value}</p><p className="mt-2 text-xs leading-5 text-subtle">{detail}</p></article>}
function Metric({label,value,note,icon,primary,danger}:{label:string;value:string|number;note:string;icon:React.ReactNode;primary?:boolean;danger?:boolean}){return <article className={`rounded-card border p-5 shadow-card ${primary?'border-primary-600 bg-gradient-to-br from-primary-600 to-primary-800 text-white':'border-line bg-panel'}`}><div className="flex items-start justify-between"><div><p className={`text-xs font-semibold uppercase tracking-wider ${primary?'text-primary-100':'text-subtle'}`}>{label}</p><p className={`mt-2 text-xl font-bold ${primary?'text-white':danger?'text-danger':'text-navy'}`}>{value}</p></div><span className={`flex h-10 w-10 items-center justify-center rounded-input ${primary?'bg-white/15':'border border-line bg-surface text-primary-600'}`}>{icon}</span></div><p className={`mt-3 text-xs ${primary?'text-primary-100':'text-subtle'}`}>{note}</p></article>}
