import { Link, useSearchParams } from 'react-router-dom';
import { DetailSheet } from '../../../components/ui/DetailSheet';
import { Button } from '../../../components/ui/Button';
import { EmptyState, ErrorState } from '../../../components/states';
import { formatRupiah, formatDate, channelLabels } from '../ui/format';
import { StatusBadge } from '../ui/StatusBadge';
import { WorkflowGuide } from '../ui/WorkflowGuide';
import { useState, type FormEvent } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { depositsApi, type DepositInput, type DepositSource } from '../api/deposits';
import { useAuth } from '../../../session/AuthContext';
import { hasCapability } from '../../../session/capability';
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jakarta',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const blank=():DepositInput=>({omzet_id:'',channel:'',deposit_date:today(),amount:'',destination:'',source_reference:'',evidence_reference:''});
const inputClass='mt-1 w-full rounded-lg border border-line bg-panel p-2';
export default function AccountingDepositsPage(){
 const [params]=useSearchParams();const sourceFilter=params.get('omzet_id');
 return <DepositWorkspace key={sourceFilter===null?'monthly':`source:${sourceFilter}`} sourceFilter={sourceFilter}/>;
}
function DepositWorkspace({sourceFilter}:{sourceFilter:string|null}){
 const {user}=useAuth();const can=(c:string)=>!!user&&hasCapability(user.role,c,user.divisionCode);const client=useQueryClient();
 const sourceFiltered=sourceFilter!==null;const validSource=!!sourceFilter&&/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i.test(sourceFilter);
 const [formOpen,setFormOpen]=useState(false);
 const [params]=useSearchParams();const requestedMonth=params.get('month');
 const [month,setMonth]=useState(requestedMonth&&/^20\d{2}-(0[1-9]|1[0-2])$/.test(requestedMonth)?requestedMonth:today().slice(0,7));const [page,setPage]=useState(1);const [sourceMonth,setSourceMonth]=useState(today().slice(0,7));const [sourcePage,setSourcePage]=useState(1);const [source,setSource]=useState<DepositSource|null>(null);
 const [form,setForm]=useState(blank);const [selected,setSelected]=useState<string|null>(null);const [receipt,setReceipt]=useState({received_date:today(),amount:'',evidence_reference:''});const [cancel,setCancel]=useState<{receipt?:string}|null>(null);const [reason,setReason]=useState('');const [notice,setNotice]=useState('');
 const list=useQuery({queryKey:['acc-deposits','list',sourceFiltered?'source':'month',sourceFiltered?sourceFilter:month,page],queryFn:()=>sourceFiltered?depositsApi.list(month,page,sourceFilter!):depositsApi.list(month,page),enabled:can('view:acc_deposits')&&(sourceFiltered?validSource:/^\d{4}-\d{2}$/.test(month))});
 const sources=useQuery({queryKey:['acc-deposits','sources',sourceMonth,sourcePage],queryFn:()=>depositsApi.sources(sourceMonth,sourcePage),enabled:!sourceFiltered&&can('write:acc_deposits')&&/^\d{4}-\d{2}$/.test(sourceMonth)});
 const detail=useQuery({queryKey:['acc-deposits','detail',selected],queryFn:()=>depositsApi.detail(selected!),enabled:can('view:acc_deposits')&&!!selected});const record=detail.data?.data;
 const mutation=useMutation({mutationFn:async(action:'create'|'receive'|'void')=>{
  if(action==='create')return {action,result:await depositsApi.create(form)};
  if(!record)throw new Error('Muat detail setoran terlebih dahulu.');
  return {action,result:action==='receive'?await depositsApi.receive(record,receipt):await depositsApi.void(record,reason,cancel?.receipt)};
 },onSuccess:({action,result})=>{setSelected(result.data.id);client.setQueryData(['acc-deposits','detail',result.data.id],result);void client.invalidateQueries({queryKey:['acc-deposits']});setNotice('Catatan disimpan beserta histori.');if(action==='create'){setFormOpen(false);setForm(blank());setSource(null);}if(action==='receive')setReceipt({received_date:today(),amount:'',evidence_reference:''});setCancel(null);setReason('');}});
 const submit=(a:'create'|'receive'|'void')=>(e:FormEvent)=>{e.preventDefault();if(!mutation.isPending){setNotice('');mutation.mutate(a);}};
 const field=(label:string,key:keyof DepositInput,type='text')=><label className="block text-sm">{label}<input required type={type} maxLength={255} className={inputClass} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} {...(key==='amount'?{inputMode:'decimal' as const,pattern:'[0-9]{1,12}(\.[0-9]{1,2})?'}:{})}/></label>;
 const button=(label:string)=><Button type="submit" disabled={mutation.isPending}>{mutation.isPending?'Menyimpan...':label}</Button>;
 if(!can('view:acc_deposits'))return <p role="alert" className="p-6">Akses rekap setoran tidak tersedia untuk akun ini.</p>;
 return <div className="space-y-6">
  <header className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-bold">Rekap Setoran</h1><p className="mt-2 text-sm text-muted">Setoran berdasarkan omzet tervalidasi. Penerimaan dicatat Finance dari bukti aktual; sisa belum diterima bukan laba atau rugi.</p></div>{!sourceFiltered&&can('write:acc_deposits')&&<Button onClick={()=>{setSelected(null);setFormOpen(true);setNotice('');mutation.reset();}}>Buat setoran</Button>}</header>
  <WorkflowGuide kind="setoran" />
  <Link to="/accounting/kas-bank/pencocokan" className="inline-flex min-h-10 items-center text-sm font-semibold text-primary-700 dark:text-primary-300 underline">Cocokkan pembayaran omzet dengan setoran dan penerimaan</Link>
  {notice&&!selected&&<p role="status" className="text-green-700">{notice}</p>}{mutation.error&&!formOpen&&!selected&&<p role="alert" className="text-red-700">{mutation.error.message}</p>}
  {[list].filter(q=>q.error).map((q,i)=><p role="alert" key={i}>{q.error?.message}<button className="ml-3 underline" onClick={()=>void q.refetch()}>Coba lagi</button></p>)}
  {can('write:acc_deposits')&&<DetailSheet isOpen={formOpen} onClose={()=>!mutation.isPending&&setFormOpen(false)} size="xl" title="Catat setoran" subtitle="Pilih sumber omzet tervalidasi lalu catat bukti setoran.">
   {mutation.error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{mutation.error.message}</p>}
   {sources.error&&<ErrorState description={sources.error.message} onRetry={()=>void sources.refetch()} />}
   <label className="mt-3 block text-sm">Bulan omzet sumber<input type="month" required className={inputClass} value={sourceMonth} onChange={e=>{setSourceMonth(e.target.value);setSourcePage(1);}}/></label>
   {sources.isLoading&&<p role="status">Memuat sumber...</p>}{sources.isSuccess&&sources.data.data.total===0&&<EmptyState title="Belum ada omzet tervalidasi pada bulan ini" description="Pilih bulan lain atau selesaikan pemeriksaan omzet terlebih dahulu." action={<Link to="/accounting/pendapatan/rekap" className="text-primary-700 dark:text-primary-300 underline">Buka Rekap Omzet</Link>} />}<p className="my-2 text-sm">{sources.data?.data.total??0} omzet tervalidasi; 50 per halaman.</p>
   {(sources.data?.data.total??0)>50&&<nav aria-label="Halaman sumber omzet" className="flex items-center gap-3 text-sm"><button className="min-h-10 rounded border border-line px-3 disabled:opacity-40" disabled={sourcePage===1} onClick={()=>setSourcePage(sourcePage-1)}>Sebelumnya</button><span>Halaman {sourcePage}</span><button className="min-h-10 rounded border border-line px-3 disabled:opacity-40" disabled={sourcePage*50>=(sources.data?.data.total??0)} onClick={()=>setSourcePage(sourcePage+1)}>Berikutnya</button></nav>}
   {((sources.data?.data.items.length??0)>0||!!source)&&<form aria-label="Catat setoran" className="mt-3" onSubmit={submit('create')}><fieldset disabled={mutation.isPending||!sources.isSuccess||!(sources.data.data.items.length||source)} className="grid gap-3 sm:grid-cols-2">
    <label className="text-sm">Omzet tervalidasi<select required className={inputClass} value={form.omzet_id} onChange={e=>{setSource(sources.data?.data.items.find(s=>s.id===e.target.value)??null);setForm({...form,omzet_id:e.target.value,channel:''});}}><option value="">Pilih sumber</option>{source&&!sources.data?.data.items.some(s=>s.id===source.id)&&<option value={source.id}>{source.outlet_name} / {formatDate(source.business_date)} / {source.shift}</option>}{sources.data?.data.items.map(s=><option key={s.id} value={s.id}>{s.outlet_name} / {formatDate(s.business_date)} / {s.shift} / {s.source_reference}</option>)}</select></label>
    <label className="text-sm">Kanal pembayaran<select required className={inputClass} value={form.channel} onChange={e=>setForm({...form,channel:e.target.value})}><option value="">Pilih kanal</option>{(['cash','qris','edc','transfer','other'] as const).map(c=><option key={c} value={c}>{channelLabels[c]} — tersedia {source?formatRupiah((sources.data?.data.items.find(s=>s.id===form.omzet_id)??source)![`${c}_available`]):'—'}</option>)}</select></label>
    {field('Tanggal setoran','deposit_date','date')}{field('Nominal setoran (Rp, titik untuk desimal)','amount')}{field('Rekening/lokasi tujuan sesuai sumber','destination')}{field('Referensi sumber setoran unik','source_reference')}{field('Referensi dokumen bukti setoran','evidence_reference')}
    <p className="text-sm text-subtle">Bukti berupa referensi dokumen eksternal. Koreksi setoran melalui pembatalan sebelum ada penerimaan, lalu catat sumber baru.</p><div>{button('Simpan setoran')}</div>
   </fieldset></form>}</DetailSheet>}
  <section className="rounded-xl border border-line bg-panel p-4">{sourceFiltered?<div className="space-y-2"><h2 className="font-semibold text-navy">Setoran dari sumber yang dipilih</h2>{list.data?.data.source&&<p className="break-words text-sm">{list.data.data.source.outlet_name} · {formatDate(list.data.data.source.business_date)} · shift {list.data.data.source.shift} · referensi {list.data.data.source.source_reference}</p>}<p className="text-sm text-subtle">Semua tanggal setoran untuk sumber ini, termasuk bulan sesudah omzet. Catatan dibatalkan tetap tampil untuk penelusuran.</p><Link to="/accounting/kas-bank/setoran" className="inline-flex min-h-10 items-center text-sm font-semibold text-primary-700 dark:text-primary-300 underline">Semua setoran</Link>{!validSource&&<p role="alert">ID sumber omzet tidak valid. Kembali ke daftar atau laporan pencocokan.</p>}</div>:<label className="block text-sm">Bulan tanggal setoran<input type="month" required value={month} className={inputClass} onChange={e=>{setMonth(e.target.value);setPage(1);}}/></label>}
   {list.isLoading&&<p role="status">Memuat setoran...</p>}{list.isSuccess&&list.data.data.total===0&&<EmptyState title={sourceFiltered?'Belum ada setoran untuk sumber ini':'Belum ada setoran pada bulan ini'} description={sourceFiltered?'Sumber sudah ditemukan, tetapi belum mempunyai catatan setoran. Buka semua setoran untuk pencatatan baru.':'Setoran yang dicatat akan muncul di sini. Gunakan filter bulan untuk melihat periode lainnya.'} />}
   <ul className="my-4 space-y-2">{list.data?.data.items.map(r=><li key={r.id}><button disabled={mutation.isPending} className="w-full rounded-lg border border-line p-3 text-left" onClick={()=>{setSelected(r.id);setCancel(null);setReason('');mutation.reset();}}>{r.outlet_name} / {formatDate(r.business_date)} / {r.shift} — {channelLabels[r.channel]??r.channel}<br/><span className="text-sm">{formatDate(r.deposit_date)} · {formatRupiah(r.amount)} · diterima {formatRupiah(r.received_amount)} · sisa {formatRupiah(r.remaining_amount)} · <StatusBadge status={r.status} label={r.status==='voided'?'Dibatalkan':'Dicatat'} /></span></button></li>)}</ul>
   {(list.data?.data.total??0)>0&&<nav aria-label="Halaman daftar setoran" className="flex flex-wrap items-center gap-3 text-sm"><button className="min-h-10 rounded border border-line px-3 disabled:opacity-40" disabled={page===1} onClick={()=>setPage(page-1)}>Sebelumnya</button><span>Halaman {page} · {list.data?.data.total??0} catatan</span><button className="min-h-10 rounded border border-line px-3 disabled:opacity-40" disabled={page*50>=(list.data?.data.total??0)} onClick={()=>setPage(page+1)}>Berikutnya</button></nav>}
  </section>
  {selected&&<DetailSheet isOpen onClose={()=>!mutation.isPending&&setSelected(null)} size="xl" title={record?`Detail — ${record.source_reference}`:'Detail setoran'}>{detail.isLoading?<p role="status">Memuat detail...</p>:detail.error?<ErrorState description={detail.error.message} onRetry={()=>void detail.refetch()}/>:record&&<div className="space-y-4">
   {mutation.error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{mutation.error.message}</p>}{notice&&<p role="status" className="text-green-700">{notice}</p>}
   <p>{record.outlet_name} / {formatDate(record.business_date)} / {record.shift} · {channelLabels[record.channel]??record.channel}</p><p>Tujuan: {record.destination} · bukti: {record.evidence_reference}</p><p>Setoran {formatRupiah(record.amount)} · diterima {formatRupiah(record.received_amount)} · sisa {formatRupiah(record.remaining_amount)} · versi {record.version} · <StatusBadge status={record.status} label={record.status==='voided'?'Dibatalkan':'Dicatat'} /></p>
   {record.status==='recorded'&&can('receive:acc_deposits')&&record.created_by!==user?.id&&<form aria-label="Catat penerimaan" onSubmit={submit('receive')}><fieldset disabled={mutation.isPending} className="grid gap-3 md:grid-cols-3"><legend className="mb-2 font-semibold">Catat penerimaan aktual</legend>{(['received_date','amount','evidence_reference'] as const).map(k=><label key={k} className="text-sm">{{received_date:'Tanggal penerimaan',amount:'Nominal diterima (Rp)',evidence_reference:'Referensi bukti penerimaan unik'}[k]}<input required maxLength={255} type={k==='received_date'?'date':'text'} className={inputClass} value={receipt[k]} onChange={e=>setReceipt({...receipt,[k]:e.target.value})} {...(k==='amount'?{inputMode:'decimal' as const,pattern:'[0-9]{1,12}(\.[0-9]{1,2})?'}:{})}/></label>)}<div>{button('Simpan penerimaan')}</div></fieldset></form>}
   <h3 className="font-semibold">Penerimaan</h3><ul className="space-y-2">{record.receipts?.map(r=><li key={r.id} className="rounded border border-line p-2">{formatDate(r.received_date)} · {formatRupiah(r.amount)} · {r.evidence_reference} · <StatusBadge status={r.status} label={r.status==='voided'?'Dibatalkan':'Dicatat'} /> {r.status==='recorded'&&(can('void:acc_deposits')||(can('receive:acc_deposits')&&r.created_by===user?.id))&&<button disabled={mutation.isPending} className="ml-3 text-red-700 underline" onClick={()=>{setCancel({receipt:r.id});setReason('');}}>Batalkan catatan penerimaan</button>}</li>)}</ul>{record.receipts?.length===0&&<p>Belum ada penerimaan.</p>}
   {record.status==='recorded'&&record.receipts?.length===0&&(can('void:acc_deposits')||(can('write:acc_deposits')&&record.created_by===user?.id))&&<button disabled={mutation.isPending} className="text-red-700 underline" onClick={()=>{setCancel({});setReason('');}}>Batalkan setoran</button>}
   {cancel&&<form aria-label="Batalkan catatan" onSubmit={submit('void')}><fieldset disabled={mutation.isPending} className="space-y-2 rounded border border-red-200 p-3"><p>{cancel.receipt?'Pembatalan catatan penerimaan merupakan koreksi pencatatan, bukan pengembalian dana.':'Pembatalan setoran tersimpan dalam histori.'}</p><label className="block text-sm">Alasan pembatalan<textarea required minLength={10} maxLength={2000} className={inputClass} value={reason} onChange={e=>setReason(e.target.value)}/></label>{button('Konfirmasi pembatalan')}<button type="button" className="ml-3 underline" onClick={()=>setCancel(null)}>Kembali</button></fieldset></form>}
   <details><summary className="cursor-pointer font-semibold">Histori perubahan</summary><ol className="mt-3 space-y-3">{record.events?.map(e=><li key={e.version}><p>Versi {e.version} · {{created:'Setoran dibuat',receive:'Penerimaan dicatat',void:'Setoran dibatalkan',void_receipt:'Penerimaan dibatalkan'}[e.action]??e.action} · {e.actor_role} · {e.created_at}</p>{e.reason&&<p>{e.reason}</p>}<details><summary className="cursor-pointer text-sm">Data saat perubahan</summary><p className="text-sm">Setoran {formatRupiah(e.snapshot.amount)} · diterima {formatRupiah(e.snapshot.received_amount)} · sisa {formatRupiah(e.snapshot.remaining_amount)} · {String(e.snapshot.destination)} · bukti {String(e.snapshot.evidence_reference)}</p><ul className="text-sm">{e.snapshot.receipts.map(r=><li key={r.id}>{formatDate(r.received_date)} · {formatRupiah(r.amount)} · {r.evidence_reference} · <StatusBadge status={r.status} label={r.status==='voided'?'Dibatalkan':'Dicatat'} /></li>)}</ul></details></li>)}</ol></details>
  </div>}</DetailSheet>}
 </div>;
}
